I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 199, in script
    "Vous infligez [player__damage] dégats à l'ennemi."
KeyError: u'player__damage'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 199, in script
    "Vous infligez [player__damage] dégats à l'ennemi."
  File "D:\Users\xakuyer\Desktop\Python\renpy-6.99.12.4-sdk\renpy\ast.py", line 613, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "D:\Users\xakuyer\Desktop\Python\renpy-6.99.12.4-sdk\renpy\exports.py", line 1147, in say
    who(what, interact=interact)
  File "D:\Users\xakuyer\Desktop\Python\renpy-6.99.12.4-sdk\renpy\character.py", line 868, in __call__
    what = what_pattern.replace("[what]", sub(what, translate=translate))
  File "D:\Users\xakuyer\Desktop\Python\renpy-6.99.12.4-sdk\renpy\character.py", line 850, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "D:\Users\xakuyer\Desktop\Python\renpy-6.99.12.4-sdk\renpy\substitutions.py", line 232, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 605, in get_value
KeyError: u'player__damage'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Tower-Of-God 1.0
